### ISSUE TITLE
How to install apk in samsung smart TV

### ISSUE THREAD

**Issue by trondo2002** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#64]
hi 

please let me know the steps how to install the tv box version on the smart samsung tv
to able to use it 

thank you

**Comment by whmcs-smarters** [comment]
you can use Fire TV stick then install the APK into your Fire TV stick using ES File Explorer or another way. 

Or, you can buy any Android box then install the App to your android box. 

It can't be installed directly on your Smart TV because it's not a smart TV App. it's an Android App that works on Android Platform
